export const RMW_RET_OK = 0;
export const RMW_RET_ERROR = 1;
export const RMW_RET_TIMEOUT = 2;
export const RMW_RET_UNSUPPORTED = 3;
export const RMW_RET_BAD_ALLOC = 10;
export const RMW_RET_INVALID_ARGUMENT = 11;
export const RMW_RET_INCORRECT_RMW_IMPLEMENTATION = 12;
export const RMW_RET_NODE_NAME_NON_EXISTENT = 203;
export const RCL_RET_OK = RMW_RET_OK;
export const RCL_RET_ERROR = RMW_RET_ERROR;
export const RCL_RET_TIMEOUT = RMW_RET_TIMEOUT;
export const RCL_RET_BAD_ALLOC = RMW_RET_BAD_ALLOC;
export const RCL_RET_INVALID_ARGUMENT = RMW_RET_INVALID_ARGUMENT;
export const RCL_RET_UNSUPPORTED = RMW_RET_UNSUPPORTED;
export const RCL_RET_ALREADY_INIT = 100;
export const RCL_RET_NOT_INIT = 101;
export const RCL_RET_MISMATCHED_RMW_ID = 102;
export const RCL_RET_TOPIC_NAME_INVALID = 103;
export const RCL_RET_SERVICE_NAME_INVALID = 104;
export const RCL_RET_UNKNOWN_SUBSTITUTION = 105;
export const RCL_RET_ALREADY_SHUTDOWN = 106;
export const RCL_RET_NODE_INVALID = 200;
export const RCL_RET_NODE_INVALID_NAME = 201;
export const RCL_RET_NODE_INVALID_NAMESPACE = 202;
export const RCL_RET_NODE_NAME_NON_EXISTENT = 203;
export const RCL_RET_PUBLISHER_INVALID = 300;
export const RCL_RET_SUBSCRIPTION_INVALID = 400;
export const RCL_RET_SUBSCRIPTION_TAKE_FAILED = 401;
export const RCL_RET_CLIENT_INVALID = 500;
export const RCL_RET_CLIENT_TAKE_FAILED = 501;
export const RCL_RET_SERVICE_INVALID = 600;
export const RCL_RET_SERVICE_TAKE_FAILED = 601;
export const RCL_RET_TIMER_INVALID = 800;
export const RCL_RET_TIMER_CANCELED = 801;
export const RCL_RET_WAIT_SET_INVALID = 900;
export const RCL_RET_WAIT_SET_EMPTY = 901;
export const RCL_RET_WAIT_SET_FULL = 902;
export const RCL_RET_INVALID_REMAP_RULE = 1001;
export const RCL_RET_WRONG_LEXEME = 1002;
export const RCL_RET_INVALID_ROS_ARGS = 1003;
export const RCL_RET_INVALID_PARAM_RULE = 1010;
export const RCL_RET_INVALID_LOG_LEVEL_RULE = 1020;
export const RCL_RET_EVENT_INVALID = 2000;
export const RCL_RET_EVENT_TAKE_FAILED = 2001;
export const RCL_RET_LIFECYCLE_STATE_REGISTERED = 3000;
export const RCL_RET_LIFECYCLE_STATE_NOT_REGISTERED = 3001;
export const RCUTILS_ERROR_MESSAGE_MAX_LENGTH = 1024;
export const RMW_GID_STORAGE_SIZE = 16;
export const RCUTILS_S_TO_NS = (seconds: number) => seconds * 1e9;
export const RCUTILS_MS_TO_NS = (milliseconds: number) => milliseconds * 1e6;
export const RCUTILS_US_TO_NS = (microseconds: number) => microseconds * 1e3;
export const RCUTILS_NS_TO_S = (nanoseconds: number) => nanoseconds / 1e9;
export const RCUTILS_NS_TO_MS = (nanoseconds: number) => nanoseconds / 1e6;
export const RCUTILS_NS_TO_US = (nanoseconds: number) => nanoseconds / 1e3;
export const RCUTILS_RET_OK = 0;
export const RCUTILS_RET_WARN = 1;
export const RCUTILS_RET_ERROR = 2;
export const RCUTILS_RET_BAD_ALLOC = 10;
export const RCUTILS_RET_INVALID_ARGUMENT = 11;
export const RCUTILS_RET_NOT_ENOUGH_SPACE = 12;
export const RCUTILS_RET_NOT_INITIALIZED = 13;
export const RCUTILS_RET_NOT_FOUND = 14;
export const RCUTILS_RET_STRING_MAP_ALREADY_INIT = 30;
export const RCUTILS_RET_STRING_MAP_INVALID = 31;
export const RCUTILS_RET_STRING_KEY_NOT_FOUND = 32;
export const RCUTILS_RET_LOGGING_SEVERITY_MAP_INVALID = 40;
export const RCUTILS_RET_LOGGING_SEVERITY_STRING_INVALID = 41;
export const RCUTILS_RET_HASH_MAP_NO_MORE_ENTRIES = 50;
