name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Setup repo
      uses: actions/checkout@v3

    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.5
      with:
        required-ros-distributions: humble

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.29.4

    - name: Verify formatting
      run: deno fmt --check

    - name: Run linter
      run: deno lint

    - name: Run tests
      run: "source /opt/ros/humble/setup.bash && deno test -A --unstable"
